android/src/main/kotlin/com/situm/situm_flutter_wayfinding/SitumMapPlatformView.kt, lib/src/controller.dart, lib/src/definitions.dart
- Add new field `poiInfoHtml` to `OnPoiSelectedResult`
- Add `OnNavigationListener` connector to flutter wyf library
=> Feature/add poi description (Android only)

azure-pipelines.yml, example/pubspec.lock, ios/situm_flutter_wayfinding.podspec, pubspec.yaml
Situm automatic merge Release 0.0.15
=> Automatic merge into master-test to Release 0.0.15

azure-pipelines.yml, example/pubspec.lock, ios/situm_flutter_wayfinding.podspec, pubspec.yaml
Situm automatic merge Release 0.0.15
=> Automatic merge into develop-test to Release 0.0.15

example/ios/Podfile.lock, example/pubspec.lock, ios/situm_flutter_wayfinding.podspec, pubspec.yaml
Situm automatic merge Release 0.0.15
=> Automatic merge into develop to Release 0.0.15

android/build.gradle, example/pubspec.lock, ios/situm_flutter_wayfinding.podspec, pubspec.yaml
Situm automatic merge Release 0.0.16
=> Automatic merge into develop to Release 0.0.16

azure-pipelines.yml, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.1
=> Automatic merge into develop to Release 3.0.1

android/build.gradle, azure-pipelines.yml, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.2
=> Automatic merge into master to Release 3.0.2

android/build.gradle, azure-pipelines.yml, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.2
=> Automatic merge into develop to Release 3.0.2

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.3
=> Automatic merge into develop to Release 3.0.3

CHANGELOG_UNRELEASED.md, example/lib/main.dart, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.4
=> Automatic merge into develop to Release 3.0.4

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.5
=> Automatic merge into master to Release 3.0.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.5
=> Automatic merge into develop to Release 3.0.5

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.6
=> Automatic merge into master to Release 3.0.6

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.0.6
=> Automatic merge into develop to Release 3.0.6

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.1.0
=> Automatic merge into develop to Release 3.1.0

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.1.1
=> Automatic merge into develop to Release 3.1.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.1.2
=> Automatic merge into master to Release 3.1.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.1.2
=> Automatic merge into develop to Release 3.1.2

CHANGELOG_UNRELEASED.md, example/lib/main.dart, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.2.0
=> Automatic merge into develop to Release 3.2.0

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.2.2
=> Automatic merge into develop to Release 3.2.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.2.3
=> Automatic merge into master to Release 3.2.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.2.3
=> Automatic merge into develop to Release 3.2.3

CHANGELOG_UNRELEASED.md, android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.3.0
=> Automatic merge into master to Release 3.3.0

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.3.0
=> Automatic merge into develop to Release 3.3.0

CHANGELOG_UNRELEASED.md, lib/src/adapters/location_status_adapter.dart
Fix the following issues:
- CALCULATING wasn't thrown from the 2nd positioning session onwards
- CALCULATING being sent a little bit after in Android platform.
I've changed the CALCULATING to STARTING.
=> Fix CALCULATING status issues

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.3.1
=> Automatic merge into develop to Release 3.3.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.3.2
=> Automatic merge into develop to Release 3.3.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.3.3
=> Automatic merge into master to Release 3.3.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.3.3
=> Automatic merge into develop to Release 3.3.3

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.4.0
=> Automatic merge into develop to Release 3.4.0

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.4.1
=> Automatic merge into develop to Release 3.4.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.4.2
=> Automatic merge into master to Release 3.4.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.4.2
=> Automatic merge into develop to Release 3.4.2

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.4.3
=> Automatic merge into master to Release 3.4.3

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.4.3
=> Automatic merge into develop to Release 3.4.3

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, lib/src/controller.dart, lib/src/definitions.dart, lib/src/sdk_definitions.dart, lib/src/sdk_mapper.dart, lib/wayfinding.dart, pubspec.yaml
Situm automatic merge Release 3.5.0
=> Automatic merge into develop to Release 3.5.0

example/pubspec.lock, ios/situm_flutter.podspec, lib/src/controller.dart, lib/src/definitions.dart, pubspec.yaml
Situm automatic merge Release 3.5.1
=> Automatic merge into master to Release 3.5.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.1
=> Automatic merge into develop to Release 3.5.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.2
=> Automatic merge into master to Release 3.5.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.2
=> Automatic merge into develop to Release 3.5.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.3
=> Automatic merge into master to Release 3.5.3

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.3
=> Automatic merge into develop to Release 3.5.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.4
=> Automatic merge into master to Release 3.5.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.4
=> Automatic merge into develop to Release 3.5.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.5
=> Automatic merge into master to Release 3.5.5

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.5
=> Automatic merge into develop to Release 3.5.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.6
=> Automatic merge into master to Release 3.5.6

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.6
=> Automatic merge into develop to Release 3.5.6

android/build.gradle, example/azure/build-examples.yaml, example/pubspec.lock, ios/situm_flutter.podspec, lib/src/definitions.dart, lib/src/sdk_definitions.dart, pubspec.yaml
Situm automatic merge Release 3.5.7
=> Automatic merge into master to Release 3.5.7

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.5.7
=> Automatic merge into develop to Release 3.5.7

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.0
=> Automatic merge into develop to Release 3.6.0

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.1
=> Automatic merge into master to Release 3.6.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.1
=> Automatic merge into develop to Release 3.6.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.2
=> Automatic merge into master to Release 3.6.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.2
=> Automatic merge into develop to Release 3.6.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.3
=> Automatic merge into master to Release 3.6.3

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.4
=> Automatic merge into master to Release 3.6.4

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.4
=> Automatic merge into develop to Release 3.6.4

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.5
=> Automatic merge into master to Release 3.6.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.5
=> Automatic merge into develop to Release 3.6.5

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.6
=> Automatic merge into master to Release 3.6.6

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.6.6
=> Automatic merge into develop to Release 3.6.6

CHANGELOG_UNRELEASED.md, example/ios/Podfile.lock, example/lib/main.dart, lib/src/controller.dart, lib/wayfinding.dart
Mapping for the new "cartography.select_poi_category" map viewer action
=> Select poi category mapping

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.8.0
=> Automatic merge into develop to Release 3.8.0

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.8.1
=> Automatic merge into develop to Release 3.8.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.8.2
=> Automatic merge into master to Release 3.8.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.8.2
=> Automatic merge into develop to Release 3.8.2

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.9.0
=> Automatic merge into develop to Release 3.9.0

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.9.1
=> Automatic merge into develop to Release 3.9.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.9.2
=> Automatic merge into master to Release 3.9.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.9.2
=> Automatic merge into develop to Release 3.9.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.9.3
=> Automatic merge into master to Release 3.9.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.9.3
=> Automatic merge into develop to Release 3.9.3

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.9.4
=> Automatic merge into develop to Release 3.9.4

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.9.5
=> Automatic merge into develop to Release 3.9.5

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.10.0
=> Automatic merge into develop to Release 3.10.0

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.10.1
=> Automatic merge into master to Release 3.10.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.10.1
=> Automatic merge into develop to Release 3.10.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.10.2
=> Automatic merge into develop to Release 3.10.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.10.3
=> Automatic merge into master to Release 3.10.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.10.3
=> Automatic merge into develop to Release 3.10.3

example/lib/main.dart
Now you can select any POI on the building and perform a set camera on the coordinates. It does not perform any action on the POI like select or navigate, only move the camera and show the map.
=> Add the setCamera visual helper on the example app.

android/build.gradle, example/lib/main.dart, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.10.4
=> Automatic merge into master to Release 3.10.4

example/ios/Podfile.lock, ios/situm_flutter.podspec, lib/src/situm_map_view.dart, lib/wayfinding.dart
Allow 'navigate' action for WebKit when loading iframe with srcdoc
=> Allow 'navigate' action for WebKit when loading iframe with srcdoc

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.1
=> Automatic merge into develop to Release 3.11.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.2
=> Automatic merge into master to Release 3.11.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.2
=> Automatic merge into develop to Release 3.11.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.3
=> Automatic merge into develop to Release 3.11.3

CHANGELOG_UNRELEASED.md, android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.4
=> Automatic merge into develop to Release 3.11.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.6
=> Automatic merge into develop to Release 3.11.6

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.7
=> Automatic merge into develop to Release 3.11.7

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.8
=> Automatic merge into master to Release 3.11.8

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.8
=> Automatic merge into develop to Release 3.11.8

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.9
=> Automatic merge into develop to Release 3.11.9

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.10
=> Automatic merge into master to Release 3.11.10

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.11
=> Automatic merge into master to Release 3.11.11

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.11
=> Automatic merge into develop to Release 3.11.11

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.12
=> Automatic merge into master to Release 3.11.12

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.12
=> Automatic merge into develop to Release 3.11.12

CHANGELOG_UNRELEASED.md, android/build.gradle, example/ios/Podfile, example/ios/Podfile.lock, example/ios/Runner/Info.plist, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.13
=> Automatic merge into master to Release 3.11.13

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.13
=> Automatic merge into develop to Release 3.11.13

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.14
=> Automatic merge into master to Release 3.11.14

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.14
=> Automatic merge into develop to Release 3.11.14

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.15
=> Automatic merge into master to Release 3.11.15

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.15
=> Automatic merge into develop to Release 3.11.15

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.16
=> Automatic merge into master to Release 3.11.16

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.16
=> Automatic merge into develop to Release 3.11.16

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.11.17
=> Automatic merge into develop to Release 3.11.17

example/azure-pipelines.yml
- Add pipeline auto build error manage.
=> SIS-742: Add error message to auto build Example App

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.12.1
=> Automatic merge into develop to Release 3.12.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.12.2
=> Automatic merge into master to Release 3.12.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.12.2
=> Automatic merge into develop to Release 3.12.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.12.3
=> Automatic merge into develop to Release 3.12.3

lib/src/controller.dart, lib/src/definitions.dart, lib/wayfinding.dart
* Added [MapViewController#setSearchFilter()](https://pub.dev/documentation/situm_flutter/latest/wayfinding/MapViewController/setSearchFilter.html) method to filter the cartography elements displayed on the map and search results of the bottom drawer by specifying a [SearchFilter](https://pub.dev/documentation/situm_flutter/latest/wayfinding/SearchFilter-class.html).
=> Add new search() method in MapViewController

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.13.1
=> Automatic merge into develop to Release 3.13.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.13.2
=> Automatic merge into develop to Release 3.13.2

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.13.3
=> Automatic merge into master to Release 3.13.3

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.13.3
=> Automatic merge into develop to Release 3.13.3

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.13.4
=> Automatic merge into develop to Release 3.13.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.13.5
=> Automatic merge into develop to Release 3.13.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.13.6
=> Automatic merge into master to Release 3.13.6

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.13.6
=> Automatic merge into develop to Release 3.13.6

CHANGELOG_UNRELEASED.md, lib/src/controller.dart, lib/src/definitions.dart
=> chore: deprecate setDIrectionsOptions in favor of setDirectionsOptions2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.14.0
=> Automatic merge into develop to Release 3.14.0

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.15.0
=> Automatic merge into develop to Release 3.15.0

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.15.1
=> Automatic merge into master to Release 3.15.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.15.1
=> Automatic merge into develop to Release 3.15.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.15.2
=> Automatic merge into master to Release 3.15.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.15.2
=> Automatic merge into develop to Release 3.15.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.15.3
=> Automatic merge into master to Release 3.15.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.15.3
=> Automatic merge into develop to Release 3.15.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.1
=> Automatic merge into develop to Release 3.16.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.2
=> Automatic merge into develop to Release 3.16.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.3
=> Automatic merge into develop to Release 3.16.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.4
=> Automatic merge into master to Release 3.16.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.4
=> Automatic merge into develop to Release 3.16.4

CHANGELOG_UNRELEASED.md, android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, lib/src/sdk_definitions.dart, pubspec.yaml
Situm automatic merge Release 3.16.5
=> Automatic merge into master to Release 3.16.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.5
=> Automatic merge into develop to Release 3.16.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.6
=> Automatic merge into master to Release 3.16.6

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.6
=> Automatic merge into develop to Release 3.16.6

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.16.7
=> Automatic merge into develop to Release 3.16.7

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.0
=> Automatic merge into develop to Release 3.17.0

azure-pipelines.yml, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release SIS-797
=> Automatic merge into master to Release SIS-797

azure-pipelines.yml, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release SIS-797
=> Automatic merge into develop to Release SIS-797

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.1
=> Automatic merge into master to Release 3.17.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.1
=> Automatic merge into develop to Release 3.17.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.2
=> Automatic merge into develop to Release 3.17.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.3
=> Automatic merge into master to Release 3.17.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.3
=> Automatic merge into develop to Release 3.17.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.4
=> Automatic merge into develop to Release 3.17.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.5
=> Automatic merge into master to Release 3.17.5

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.17.5
=> Automatic merge into develop to Release 3.17.5

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.18.0
=> Automatic merge into develop to Release 3.18.0

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.18.1
=> Automatic merge into develop to Release 3.18.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.18.2
=> Automatic merge into master to Release 3.18.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.18.2
=> Automatic merge into develop to Release 3.18.2

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.19.0
=> Automatic merge into develop to Release 3.19.0

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.19.1
=> Automatic merge into master to Release 3.19.1

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.0
=> Automatic merge into develop to Release 3.20.0

android/build.gradle, example/ios/Podfile.lock, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.1
=> Automatic merge into master to Release 3.20.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.2
=> Automatic merge into develop to Release 3.20.2

CHANGELOG_UNRELEASED.md, example/ios/Podfile.lock, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.3
=> Automatic merge into develop to Release 3.20.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.4
=> Automatic merge into master to Release 3.20.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.4
=> Automatic merge into develop to Release 3.20.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.5
=> Automatic merge into master to Release 3.20.5

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.5
=> Automatic merge into develop to Release 3.20.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.6
=> Automatic merge into master to Release 3.20.6

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.20.6
=> Automatic merge into develop to Release 3.20.6

CHANGELOG_UNRELEASED.md, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.21.0
=> Automatic merge into develop to Release 3.21.0

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.21.1
=> Automatic merge into master to Release 3.21.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.21.1
=> Automatic merge into develop to Release 3.21.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.22.0
=> Automatic merge into develop to Release 3.22.0

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.22.1
=> Automatic merge into master to Release 3.22.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.22.1
=> Automatic merge into develop to Release 3.22.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.1
=> Automatic merge into develop to Release 3.23.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.2
=> Automatic merge into master to Release 3.23.2

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.3
=> Automatic merge into master to Release 3.23.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.3
=> Automatic merge into develop to Release 3.23.3

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.4
=> Automatic merge into master to Release 3.23.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.4
=> Automatic merge into develop to Release 3.23.4

example/azure-pipelines.yml, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.5
=> Automatic merge into master to Release 3.23.5

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.5
=> Automatic merge into develop to Release 3.23.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.6
=> Automatic merge into develop to Release 3.23.6

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.7
=> Automatic merge into master to Release 3.23.7

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.7
=> Automatic merge into develop to Release 3.23.7

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.8
=> Automatic merge into master to Release 3.23.8

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.8
=> Automatic merge into develop to Release 3.23.8

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.9
=> Automatic merge into master to Release 3.23.9

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.9
=> Automatic merge into develop to Release 3.23.9

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.10
=> Automatic merge into master to Release 3.23.10

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.11
=> Automatic merge into develop to Release 3.23.11

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.12
=> Automatic merge into master to Release 3.23.12

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.12
=> Automatic merge into develop to Release 3.23.12

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.13
=> Automatic merge into master to Release 3.23.13

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.13
=> Automatic merge into develop to Release 3.23.13

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.14
=> Automatic merge into master to Release 3.23.14

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.14
=> Automatic merge into develop to Release 3.23.14

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.15
=> Automatic merge into develop to Release 3.23.15

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.16
=> Automatic merge into master to Release 3.23.16

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.23.16
=> Automatic merge into develop to Release 3.23.16

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.24.1
=> Automatic merge into develop to Release 3.24.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.1
=> Automatic merge into develop to Release 3.25.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.2
=> Automatic merge into master to Release 3.25.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.2
=> Automatic merge into develop to Release 3.25.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.3
=> Automatic merge into master to Release 3.25.3

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.3
=> Automatic merge into develop to Release 3.25.3

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.4
=> Automatic merge into master to Release 3.25.4

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.4
=> Automatic merge into develop to Release 3.25.4

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.5
=> Automatic merge into master to Release 3.25.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.5
=> Automatic merge into develop to Release 3.25.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.6
=> Automatic merge into master to Release 3.25.6

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.6
=> Automatic merge into develop to Release 3.25.6

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.7
=> Automatic merge into develop to Release 3.25.7

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.8
=> Automatic merge into master to Release 3.25.8

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.8
=> Automatic merge into develop to Release 3.25.8

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.9
=> Automatic merge into master to Release 3.25.9

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.9
=> Automatic merge into develop to Release 3.25.9

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.10
=> Automatic merge into master to Release 3.25.10

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.10
=> Automatic merge into develop to Release 3.25.10

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.11
=> Automatic merge into master to Release 3.25.11

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.11
=> Automatic merge into develop to Release 3.25.11

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.12
=> Automatic merge into master to Release 3.25.12

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.12
=> Automatic merge into develop to Release 3.25.12

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.13
=> Automatic merge into master to Release 3.25.13

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.13
=> Automatic merge into develop to Release 3.25.13

CHANGELOG_UNRELEASED.md, example/ios/Podfile.lock, example/ios/Runner/AppDelegate.swift, example/pubspec.lock, ios/situm_flutter.podspec, lib/src/controller.dart, pubspec.yaml
Situm automatic merge Release 3.25.14
=> Automatic merge into develop to Release 3.25.14

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.15
=> Automatic merge into master to Release 3.25.15

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.25.15
=> Automatic merge into develop to Release 3.25.15

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.0
=> Automatic merge into develop to Release 3.26.0

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.1
=> Automatic merge into master to Release 3.26.1

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.2
=> Automatic merge into master to Release 3.26.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.2
=> Automatic merge into develop to Release 3.26.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.3
=> Automatic merge into master to Release 3.26.3

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.3
=> Automatic merge into develop to Release 3.26.3

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.4
=> Automatic merge into master to Release 3.26.4

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.4
=> Automatic merge into develop to Release 3.26.4

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.5
=> Automatic merge into master to Release 3.26.5

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.5
=> Automatic merge into develop to Release 3.26.5

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.6
=> Automatic merge into master to Release 3.26.6

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.7
=> Automatic merge into develop to Release 3.26.7

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.8
=> Automatic merge into develop to Release 3.26.8

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.7
=> Automatic merge into master to Release 3.26.7

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.8
=> Automatic merge into master to Release 3.26.8

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.9
=> Automatic merge into master to Release 3.26.9

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.9
=> Automatic merge into develop to Release 3.26.9

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.10
=> Automatic merge into master to Release 3.26.10

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.10
=> Automatic merge into develop to Release 3.26.10

example/ios/Podfile.lock, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.11
=> Automatic merge into master to Release 3.26.11

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.12
=> Automatic merge into master to Release 3.26.12

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.13
=> Automatic merge into master to Release 3.26.13

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.13
=> Automatic merge into develop to Release 3.26.13

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.14
=> Automatic merge into master to Release 3.26.14

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.14
=> Automatic merge into develop to Release 3.26.14

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.15
=> Automatic merge into master to Release 3.26.15

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.16
=> Automatic merge into develop to Release 3.26.16

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.17
=> Automatic merge into master to Release 3.26.17

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.17
=> Automatic merge into develop to Release 3.26.17

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.18
=> Automatic merge into master to Release 3.26.18

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.18
=> Automatic merge into develop to Release 3.26.18

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.19
=> Automatic merge into master to Release 3.26.19

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.19
=> Automatic merge into develop to Release 3.26.19

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.20
=> Automatic merge into master to Release 3.26.20

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.20
=> Automatic merge into develop to Release 3.26.20

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.21
=> Automatic merge into master to Release 3.26.21

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.21
=> Automatic merge into develop to Release 3.26.21

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.22
=> Automatic merge into master to Release 3.26.22

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.23
=> Automatic merge into master to Release 3.26.23

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.23
=> Automatic merge into develop to Release 3.26.23

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.24
=> Automatic merge into master to Release 3.26.24

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.24
=> Automatic merge into develop to Release 3.26.24

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.25
=> Automatic merge into master to Release 3.26.25

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.25
=> Automatic merge into develop to Release 3.26.25

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.26.26
=> Automatic merge into master to Release 3.26.26

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.27.0
=> Automatic merge into develop to Release 3.27.0

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.27.1
=> Automatic merge into develop to Release 3.27.1

example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.27.2
=> Automatic merge into master to Release 3.27.2

android/build.gradle, example/pubspec.lock, ios/situm_flutter.podspec, pubspec.yaml
Situm automatic merge Release 3.27.4
=> Automatic merge into master to Release 3.27.4
